# Generated by Django 5.2.4 on 2025-07-22 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18 years'), django.core.validators.MaxValueValidator(100, message='Age cannot be more than 100 years')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Monthly salary cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_app.customer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Interest rate cannot be negative'), django.core.validators.MaxValueValidator(100, message='Interest rate cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Loan amount cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Tenure must be at least 1 month'), django.core.validators.MaxValueValidator(300, message='Tenure cannot exceed 300 months')]),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loan',
            table=None,
        ),
    ]
